Remove test from ignore list and replace sleep
Signed-off-by: varshab1210 <varshab1210@gmail.com>

diff --git a/test/openshift/e2e/parallel/1-042_validate_status_host/02-check_URL.yaml b/test/openshift/e2e/parallel/1-042_validate_status_host/02-check_URL.yaml
--- a/test/openshift/e2e/parallel/1-042_validate_status_host/02-check_URL.yaml
+++ b/test/openshift/e2e/parallel/1-042_validate_status_host/02-check_URL.yaml
@@ -2,20 +2,20 @@ apiVersion: kuttl.dev/v1beta1
 kind: TestStep
 commands:
 - script: |
-    route_URL=$(oc get routes -o jsonpath="{.items[*]['spec.host']}" --field-selector metadata.name=example-argocd-server -n $NAMESPACE)
-    status_URL=$(oc get argocd -o jsonpath="{.items[*]['status.host']}" -n $NAMESPACE)
+    until [[ $i -eq 20 ]]
+    do
+      route_URL=$(oc get routes -o jsonpath="{.items[*]['spec.host']}" --field-selector metadata.name=example-argocd-server -n $NAMESPACE)
+      status_URL=$(oc get argocd -o jsonpath="{.items[*]['status.host']}" -n $NAMESPACE)
 
-    echo -e "route_URL:${route_URL}\nstatus_URL:${status_URL}"
+      echo -e "route_URL:${route_URL}\nstatus_URL:${status_URL}"
 
-    sleep 15
-    
-    route_URL=$(oc get routes -o jsonpath="{.items[*]['spec.host']}" --field-selector metadata.name=example-argocd-server -n $NAMESPACE)
-    status_URL=$(oc get argocd -o jsonpath="{.items[*]['status.host']}" -n $NAMESPACE)
+      if ! [[ "${status_URL}" == "${route_URL}" ]]; then
+        i=$((i+1))
+        sleep 6
+      else
+        exit 0 
+      fi
+    done
 
-    echo -e "route_URL:${route_URL}\nstatus_URL:${status_URL}"
-
-    if ! [[ "${status_URL}" == "${route_URL}" ]]; then
-      echo "Error: Route does not match"
-      exit 1
-    fi
-    exit 0
+    echo "Error: Route does not match"
+    exit 1
